### ISSUE TITLE
Windows system frozes

### ISSUE THREAD

**Issue by minnyres** [dockur/windows-arm#251]
### Operating system

Ubuntu 22.04.5 LTS

### Description

The Windows system sometimes gets frozen when I am installing softwares on it. The GUI in web browser has not response. RDP cannot be connected.  The error message is `qemu-system-aarch64: Desc next is ...`

### Docker compose

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VGA: "virtio-gpu"
      VERSION: "11l"
      DISK_SIZE: "256G"
      RAM_SIZE: "16G"
      CPU_CORES: "8"
      USERNAME: "nvidia"
      PASSWORD: "nvidia"
    volumes:
      - /home/nvidia/VMs/windows-arm/disk1:/storage
      - /home/nvidia/VMs/windows-arm/data:/data
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m
```

### Docker log

❯ Starting Windows for Docker v4.11...
❯ For support visit https://github.com/dockur/windows-arm
❯ CPU: Cortex A78AE | RAM: 59/62 GB | DISK: 790 GB (ext4) | KERNEL: 5.15.148-tegra...

❯ Booting Windows using QEMU v9.2.0...
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,BFE61F76-4F8D-475F-B8C9-434AB4958E9D,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,BFE61F76-4F8D-475F-B8C9-434AB4958E9D,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
qemu-system-aarch64: Desc next is 6
