### ISSUE TITLE
Unable to deploy on ARM server

### ISSUE THREAD

**Issue by 9E307** [dockur/windows-arm#27]
I use the docker command line provided by this project on my ARM server, and the system prompts "Error response from daemon: error gathering device information while adding custom device "/dev/kvm": no such file or directory."

Then I used the "cpu-checker" command to query and it showed "FATAL: Module msr not found in directory /lib/modules/6.2.0-39-generic". So is it because my server does not support KVM?

**Comment by bywenshu** [comment]
May I know where to add `KVM=N`?

**Comment by bywenshu** [comment]
```
version: "3"
services:
  windows:
    image: dockurr/windows-arm
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "160G"

    stop_grace_period: 2m
    restart: on-failure
```
