### ISSUE TITLE
ERROR: Status 1 while: ip tuntap add dev "$VM_NET_TAP" mode tap (line 163/295)

### ISSUE THREAD

**Issue by nongze** [dockur/windows-arm#29]
ERROR: Status 1 while: ip tuntap add dev "$VM_NET_TAP" mode tap (line 163/295)
```
root@orangepi5:~# docker run -it --rm -p 8007:8006 --device=/dev/kvm --cap-add NET_ADMIN --stop-timeout 120 dockurr/windows-arm
❯ Starting Windows for Docker v1.07...
❯ For support visit https://github.com/dockur/windows-arm

❯ Downloading product information from Microsoft...
❯ Downloading Windows 11 for ARM...
/storage/tmp/win11arm64.esd   100%[=================================================>]   4.88G  7.99MB/s    in 10m 48s
❯ Extracting Windows 11 for ARM bootdisk...
❯ Extracting Windows 11 for ARM environment...
❯ Extracting Windows 11 for ARM setup...
❯ Extracting Windows 11 for ARM image...
❯ Adding XML file for automatic installation...
❯ Building Windows 11 for ARM image...
❯ Creating a 64G growable disk image in raw format...
open: No such device
❯ ERROR: Status 1 while: ip tuntap add dev "$VM_NET_TAP" mode tap (line 163/295)
```
OS:Linux orangepi5 5.10.110-rockchip-rk3588 #1.1.6 SMP Thu Jun 1 21:23:54 CST 2023 aarch64 GNU/Linux(debian12)
I'm just a rookie, I don't know what this is about, I don't know how to do it, thanks.

**Comment by nongze** [comment]
```
root@orangepi5:~# docker run -it --rm -p 8007:8006 --device=/dev/kvm **--device /dev/net/tun:/dev/net/tun** --cap-add NET_ADMIN --stop-timeout 120 dockurr/windows-arm
❯ Starting Windows for Docker v1.07...
❯ For support visit https://github.com/dockur/windows-arm

❯ Downloading product information from Microsoft...
❯ Downloading Windows 11 for ARM...
/storage/tmp/win11arm64.esd   100%[=================================================>]   4.88G  3.72MB/s    in 23m 3s
❯ Extracting Windows 11 for ARM bootdisk...
❯ Extracting Windows 11 for ARM environment...
❯ Extracting Windows 11 for ARM setup...
❯ Extracting Windows 11 for ARM image...
❯ Adding XML file for automatic installation...
❯ Building Windows 11 for ARM image...
❯ Creating a 64G growable disk image in raw format...
open: No such device
❯ ERROR: Status 1 while: ip tuntap add dev "$VM_NET_TAP" mode tap (line 163/295)
```
It still doesn't work.

**Comment by nongze** [comment]
This is feasible!
But I encountered a new problem.
```
root@orangepi5:~# docker run -it --rm -p 8007:8006 --device=/dev/kvm --device /dev/net/tun:/dev/net/tun --cap-add NET_ADMIN --stop-timeout 120 dockurr/windows-arm
❯ Starting Windows for Docker v1.07...
❯ For support visit https://github.com/dockur/windows-arm

❯ Downloading product information from Microsoft...
❯ Downloading Windows 11 for ARM...
/storage/tmp/win11arm64.es 100%[======================================>]   4.88G  1.11MB/s    in 75m 22s 
❯ Extracting Windows 11 for ARM bootdisk...
❯ Extracting Windows 11 for ARM environment...
❯ Extracting Windows 11 for ARM setup...
❯ Extracting Windows 11 for ARM image...
❯ Adding XML file for automatic installation...
❯ Building Windows 11 for ARM image...
❯ Creating a 64G growable disk image in raw format...
iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
❯ ERROR: Status 3 while: iptables -t nat -A POSTROUTING -o "$VM_NET_DEV" -j MASQUERADE (line 178/295)

```
Is this about iptables? I tried updating APT, but it is already the latest version.
```
root@orangepi5:~# iptables --version
iptables v1.8.7 (nf_tables)
```

**Comment by nongze** [comment]
I am trying to do this now:
```
modprobe  ip_tables 
modprobe  iptable_filter
sudo echo 'ip_tables' >> /etc/modules
```

**Comment by nongze** [comment]
Another error.
```
root@orangepi5:~# docker run -it --rm -p 8007:8006 --device=/dev/kvm --device /dev/net/tun:/dev/net/tun --cap-add NET_ADMIN --stop-timeout 120 dockurr/windows-arm
❯ Starting Windows for Docker v1.07...
❯ For support visit https://github.com/dockur/windows-arm

❯ Downloading product information from Microsoft...
❯ Downloading Windows 11 for ARM...
/storage/tmp/win11arm64.es 100%[======================================>]   4.88G  11.3MB/s    in 7m 53s  
❯ Extracting Windows 11 for ARM bootdisk...
❯ Extracting Windows 11 for ARM environment...
❯ Extracting Windows 11 for ARM setup...
❯ Extracting Windows 11 for ARM image...
❯ Adding XML file for automatic installation...
❯ Building Windows 11 for ARM image...
❯ Creating a 64G growable disk image in raw format...
Warning: Extension multiport revision 0 not supported, missing kernel module?
iptables v1.8.10 (legacy): multiport.0 does not support invert
Try `iptables -h' or 'iptables --help' for more information.
❯ ERROR: Status 2 while: iptables -t nat -A PREROUTING -i "$VM_NET_DEV" -d "$IP" -p tcp${exclude} -j DNAT --to "$VM_NET_IP" (line 180/295)

```

**Comment by nongze** [comment]
I tried to manually load it, but it didn't work.
```
root@orangepi5:~# modprobe multiport
modprobe: FATAL: Module multiport not found in directory /lib/modules/5.10.110-rockchip-rk3588
```

**Comment by nongze** [comment]
```
root@orangepi5:~# docker-compose up -d
validating /root/docker-compose.yml: services.device_cgroup_rules must be a mapping

```
`docker-compose.yml`：as follows
```

version: "3"
services:
  environment:
    VERSION: "win11"
    DHCP: "Y"
  device_cgroup_rules:
    - 'c *:* rwm'
  windows:
    container_name: windows
    image: dockurr/windows-arm
    #environment:
      #VERSION: "win10"
        #DHCP: "Y"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure

```

**Comment by nongze** [comment]
Oh, I got it!
Waiting for my good news!

**Comment by nongze** [comment]
But I have confirmed that it supports macvlan
` ERROR: You can only enable DHCP while the container is on a macvlan network!`

**Comment by nongze** [comment]
Ok,It's running.But there are still some issues.
![屏幕截图 2024-03-02 141533](https://github.com/dockur/windows-arm/assets/110707694/f50a251b-5e69-413b-9543-a0937728a5fc)
![屏幕截图 2024-03-02 141506](https://github.com/dockur/windows-arm/assets/110707694/7c7c417a-2a3f-412a-b96a-6a836b978dcb)

**Comment by nongze** [comment]
After I switched to Win11, it completely resolved the issue and did not use DHCP.
**Summary:**
对于rk3588(s)设备，如Orange Pi5/5 Plus，先使用以下命令创建macvlan，`end1`为你的网卡名称.
`docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=end1 macnet0`
Then use this `docker-compose.yml`

```
version: "3"
services:
  windows:
    environment:
      VERSION: "win11"
      #DHCP: "Y"
    device_cgroup_rules:
      - 'c *:* rwm'
    container_name: windows
    image: dockurr/windows-arm
    #environment:
      #VERSION: "win10"
        #DHCP: "Y"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    networks:
      macnet0:
        ipv4_address: 192.168.1.100

networks:
  macnet0:
    external: true

```
