### ISSUE TITLE
Erroneous disk space error after downloading

### ISSUE THREAD

**Issue by yllekz** [dockur/windows-arm#31]
```
services:
  windows:
    container_name: windows
    image: dockurr/windows-arm
    #devices:
      #- /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    environment:
      - RAM_SIZE="2G"
      - CPU_CORES="2"
      - DISK_SIZE="45G"
    volumes:
      - "/path/to/my/data/folder:/storage"
    stop_grace_period: 2m
    restart: unless-stopped
```

It attempts to download the .esd file but errors out and restarts the download. Error is:

``ERROR: Not enough free space in /storage, have 9 GB available but need at least 15 GB.``

The path to my /storage is a 1TB drive. Why would such an error be thrown up?
