### ISSUE TITLE
Startup error after modifying configuration.

### ISSUE THREAD

**Issue by nongze** [dockur/windows-arm#37]
When I added configuration to Docker Compose.yml to modify RAM and CPU, there was a startup error, whether it was the first creation or modification after creation.
```
    environment:
      VERSION: "win11"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
```
```
root@orangepi5:/root/win# docker-compose up
[+] Building 0.0s (0/0)                                                                                                      docker:default
[+] Running 1/1
 ✔ Container windows  Recreated                                                                                                        0.2s 
Attaching to windows
windows  | ❯ Starting Windows for Docker v1.08...
windows  | ❯ For support visit https://github.com/dockur/windows-arm
windows  | 
windows  | ❯ Booting Windows using QEMU emulator version 8.2.1 ...
windows  | ❯ ERROR: qemu-system-aarch64: Failed to put registers after init: Invalid argument
windows exited with code 0
```
If the default configuration is used, there will be no errors.

**Comment by yuunnn-w** [comment]
> I cannot think of a reason why this happens. Because even without setting these values in your Dockerfile, they are still set to the defaults (4G and 2 cores) so if anything was wrong with the order I set them for example, it would also happen with the defaults.
> 
> I will see if I can reproduce this and fix it, but currently I have no ARM hardware available anymore (used my Pi5 for something else now), so it might take some time before I can fix this.

I suspect the issue might be due to the qemu version you are using being too old, leading to abnormal parameter passing. The error message is:  `ERROR: qemu-system-aarch64: Failed to put registers after init: Invalid argument` . Moreover, the error occurs regardless of whether the parameters in the configuration file are removed or not. The qemu version we are using is 8.2.1, and the hardware we use is OrangePi 5 Plus.

**Comment by samirdjelal** [comment]
I've got the same issue on OrangePi 5 Plus, I've used the default docker-compose without any changes or custom env vars
```
windows  | ❯ Extracting Windows 11 for ARM bootdisk...
windows  | ❯ Extracting Windows 11 for ARM environment...
windows  | ❯ Extracting Windows 11 for ARM setup...
windows  | ❯ Extracting Windows 11 for ARM image...
windows  | ❯ Adding XML file for automatic installation...
windows  | ❯ Building Windows 11 for ARM image...
windows  | ❯ Creating a 64G growable disk image in raw format...
windows  | ❯ Booting Windows using QEMU emulator version 8.2.1 ...
windows  | ❯ ERROR: qemu-system-aarch64: Failed to put registers after init: Invalid argument
windows  | ❯ Starting Windows for Docker v1.08...
windows  | ❯ For support visit https://github.com/dockur/windows-arm
```

**Comment by Explosion-Scratch** [comment]
@kroese Happening to me as well:
```
windows  | ❯ Starting Windows for Docker v1.09...
windows  | ❯ For support visit https://github.com/dockur/windows-arm
windows  |
windows  | ❯ Host: c84093f0d383  IP: 172.24.0.2  Gateway: 172.24.0.1  Interface: eth0  MAC: 02:7E:CC:0F:F0:80
windows  | nameserver 127.0.0.11
windows  |
windows  | ++ /usr/sbin/dnsmasq --dhcp-range=20.20.20.21,20.20.20.21 --dhcp-host=02:7E:CC:0F:F0:80,,20.20.20.21,QEMU,infinite --dhcp-option=option:netmask,255.255.255.0 --dhcp-option=option:dns-server,20.20.20.1 --dhcp-option=option:router,20.20.20.1 --address=/host.lan/20.20.20.1
windows  |
windows  | ❯ Booting Windows using QEMU emulator version 8.2.1 ...
windows  | Arguments: -nodefaults -cpu host -smp 4,sockets=1,dies=1,cores=4,threads=1 -m 4G -machine type=virt,secure=off,dump-guest-core=off,accel=kvm -enable-kvm -display vnc=:0,websocket=5700 -device ramfb -monitor telnet:localhost:7100,server,nowait,nodelay -daemonize -D /run/shm/qemu.log -pidfile /run/shm/qemu.pid -name windows,process=windows,debug-threads=on -serial pty -device qemu-xhci,id=xhci -device usb-kbd -device usb-tablet -netdev tap,ifname=qemu,script=no,downscript=no,id=hostnet0 -device virtio-net-pci,romfile=,netdev=hostnet0,mac=02:7E:CC:0F:F0:80,id=net0 -object iothread,id=io2 -drive id=cdrom0,media=cdrom,if=none,format=raw,readonly=on,file=/storage/win11arm64.iso -device virtio-scsi-pci,id=scsi0,iothread=io2,addr=0x5 -device scsi-cd,bus=scsi0.0,drive=cdrom0,bootindex=10 -drive id=cdrom1,media=cdrom,if=none,format=raw,readonly=on,file=/run/drivers.iso -device usb-storage,drive=cdrom1 -drive file=/storage/data.img,if=none,id=drive-userdata,format=raw,cache=none,aio=native,discard=on,detect-zeroes=on -device virtio-scsi-pci,id=hw-userdata,iothread=io2,bus=pcie.0,addr=0xa -device scsi-hd,bus=hw-userdata.0,channel=0,scsi-id=0,lun=0,drive=drive-userdata,id=userdata,rotation_rate=1,bootindex=3 -drive file=/storage/windows.rom,if=pflash,unit=0,format=raw,readonly=on -drive file=/storage/windows.vars,if=pflash,unit=1,format=raw -device virtio-balloon-pci,id=balloon0,bus=pcie.0,addr=0x4 -object rng-random,id=objrng0,filename=/dev/urandom -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pcie.0,addr=0x1c
windows  |
windows  | ❯ ERROR: qemu-system-aarch64: Failed to put registers after init: Invalid argument
windows exited with code 0
```

<details>
<summary>  `docker-compose.yml`   </summary>

```yml
version: "3"
services:
  windows:
    container_name: windows
    image: dockurr/windows-arm
    environment:
      VERSION: "win11"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DEBUG: "Y"
    volumes:
      - /home/tjs/Media/Windows:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
```


</details>

**Comment by Explosion-Scratch** [comment]
I also removed all environment variables except for VERSION and DEBUG and it's still happening.

**Comment by Explosion-Scratch** [comment]
I'm also running the Orange Pi 5B using Armbian

<details>
<summary>Screenfetch</summary>

```
❯ screenfetch
                          ./+o+-       tjs@tjsorange
                  yyyyy- -yyyyyy+      OS: Ubuntu 22.04 jammy
               ://+//////-yyyyyyo      Kernel: aarch64 Linux 5.10.160-legacy-rk35xx
           .++ .:/++++++/-.+sss/`      Uptime: 3d 1h 28m
         .:++o:  /++++++++/:--:/-      Packages: 1802
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.8.1
       .:+o:+o/.          `+sssoo+/    Disk: 1.5T / 6.0T (26%)
  .++/+:+oo+o:`             /sssooo.   CPU: ARM Cortex-A55 Cortex-A76 @ 8x 1.8GHz
 /+++//+:`oo+o               /::--:.   RAM: 4996MiB / 15718MiB
 \+/+o+++`o++o               ++////.
  .++.o+++oo+:`             /dddhhh.
       .+.o+oo:.          `oddhhhh+
        \+.++o+o``-````.:ohdhhhhh+
         `:o+++ `ohhhhhhhhyo++os:
           .o:`.syhhhhhhh/.oo++o`
               /osyyyyyyo++ooo+++/
                   ````` +oo+++o\:
                          `oo++.
```



</details>

**Comment by morsDeiGH** [comment]
Rockchip RK3588 have 4 core Cortex-A76 and 4 core Cortex-A55.
If disable 4 core Cortex-A76 or 4 core Cortex-A55 and after this container running normally, but with both core, we get an error "qemu-system-aarch64: Failed to put registers after init: Invalid argument".
1. sudo chcpu --disable 0,1,2,3
2. docker compose up
3. sudo chcpu --enable 0,1,2,3
The problem seems to be due to different kernels

**Comment by rogerdk** [comment]
I have come across the same problem. I'm also using an OrangePi5
Could I pass custom parameters for testing?
in this thread (https://github.com/Joshua-Riek/ubuntu-rockchip/issues/731#issuecomment-2127360776) they propose to use something like:  `--vcpus=4,cpuset=4-7`.

However, I have tried to disable the cpus before booting and I cannot avoid this error: 

`'ERROR: Timeout while waiting for QEMU to boot the machine!' `

even though the cpu seems high. it's as if despite not being able to connect the windows runs.

**Comment by sund3RRR** [comment]
I think the easiest solution is to override `/run/entry.sh` and change this line:
```patch
- { qemu-system-aarch64 ${ARGS:+ $ARGS} >"$QEMU_OUT" 2>"$QEMU_LOG"; rc=$?; } || :
+ { taskset -c $CPU_TASK_SET qemu-system-aarch64 ${ARGS:+ $ARGS} >"$QEMU_OUT" 2>"$QEMU_LOG"; rc=$?; } || :
```

Then add this env to the environment section of compose file:
```yml
environment:
  - CPU_TASK_SET: "4,5,6,7"
```

**Comment by sund3RRR** [comment]
Off-topic. Great work, man, thank you for windows-arm!

I don't quite understand qemu-kvm related stuff, but is it real to passthrough mali-g610 gpu? Or at least accelerate 3d with virgl adapter? I want to speed up rdp session because cpu performance is not enough :(

**Comment by sund3RRR** [comment]
> @sund3RRR I want to detect the Orange Pi, so the flag will be automaticly applied. Do you know an easy way? For example, I can check if the kernel name ends with `-rk35xx` but I dont know if all Orange Pi's always use a kernel with that name?

Hmmm. I don't know. I think this check is not enough.
At least my orangepi's kernel name is `6.1.0-1014-rockchip`

And technically orangepi can run mainline linux since 6.8 kernel version with [edk2-rk3588](https://github.com/edk2-porting/edk2-rk3588) uefi

**Comment by sund3RRR** [comment]
> Can you show me how it detects the CPU in the Docker log (the first line where it says CPU/RAM/etc)

Sure
```bash
❯ Starting Windows for Docker v2.09...
❯ For support visit https://github.com/dockur/windows-arm
❯ CPU: Cortex A55 | RAM: 6/8 GB | DISK: 362 GB (ext4) | HOST: 6.1.0-1014-rockchip...
```

**Comment by sund3RRR** [comment]
It works! Well done :)

**Comment by sund3RRR** [comment]
P.S. It doesn't work with base `qemux/qemu-arm` image due to
```bash
❯ Booting image using QEMU v8.2.4...
taskset: failed to execute exec: No such file or directory
```

Need to patch
```patch
- taskset -c "$CPU_PIN" exec qemu-system-aarch64 ${ARGS:+ $ARGS}
+ taskset -c "$CPU_PIN" qemu-system-aarch64 ${ARGS:+ $ARGS}
```

**Comment by nongze** [comment]
Can we support 8 cores in this way？
```
environment:
  - CPU_TASK_SET: "0,1,2,34,5,6,7"
```

**Comment by nongze** [comment]
After my attempt, it is feasible.
```
root@orangepi5:~# cat win/docker-compose.yml
version: "3"
services:
  windows:
    environment:
      CPU_TASK_SET: "1,2,3,4,5,6,7"
      VERSION: "win11"
      RAM_SIZE: "4G"
      CPU_CORES: "8"
    device_cgroup_rules:
      - 'c *:* rwm'
    container_name: windows
    image: dockurr/windows-arm
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    networks:
      macnet0:
        ipv4_address: 192.168.1.100

networks:
  macnet0:
    external: true
```
![image](https://github.com/dockur/windows-arm/assets/110707694/764ce87c-c6e6-432d-9ec9-0c1b6d8ccde6)

**Comment by nongze** [comment]
After my attempts, it seems to be feasible.

```
root@orangepi5:~# cat win/docker-compose.yml
version: "3"
services:
  windows:
    environment:
      CPU_TASK_SET: "1,2,3,4,5,6,7"
      VERSION: "win11"
      RAM_SIZE: "4G"
      CPU_CORES: "8"
    device_cgroup_rules:
      - 'c *:* rwm'
    container_name: windows
    image: dockurr/windows-arm
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    networks:
      macnet0:
        ipv4_address: 192.168.1.100

networks:
  macnet0:
    external: true
```
![image](https://github.com/dockur/windows-arm/assets/110707694/764ce87c-c6e6-432d-9ec9-0c1b6d8ccde6)
But the corresponding core does not have a corresponding load.
