### ISSUE TITLE
[Bug]: awk error when trying to start 1.14

### ISSUE THREAD

**Issue by jokay** [dockur/windows-arm#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Machine specifications

RaspberryPi 5 / 8 GB

### Operating system

Debian 12 (stable) 

### Docker version

26.0.1

### Description

Using version **1.12** it works but when trying to start **1.14** it fails.

### Docker compose

```yml
services:
  app:
    image: dockurr/windows-arm:1.14
    volumes:
      - ./data/storage:/storage
    environment:
      - VERSION=win11
      - RAM_SIZE=4G
      - CPU_CORES=2
      - DISK_SIZE=128G
    ports:
      - 3389:3389
      - 3389:3389/udp
    restart: on-failure
    devices:
      - /dev/kvm
    stop_grace_period: 2m
    cap_add:
      - NET_ADMIN
```

### Docker log

```sh
app-1  | ❯ Starting Windows for Docker v1.14...
app-1  | ❯ For support visit https://github.com/dockur/windows-arm
app-1  | 
app-1  | reset.sh: line 47: qemu-system-x86_64: command not found
app-1  | ❯ ERROR: Status 127 while: awk '{ print $NF }' (line 47/11)
app-1  | ❯ ERROR: Status 127 while: VERS=$(qemu-system-x86_64 --version | head -n 1 | cut -d '(' -f 1 | awk '{ print $NF }') (line 47/11)
```
